[build]
target = "x86_64-unknown-none"

rustflags = [
    "-C",
    "no-redzone=yes",
    "-C",
    "relocation-model=static",

    "-C",
    "link-arg=--image-base=0xffff800000000000",
    "-C",
    "code-model=large",
]
