[package]
name = "loader2"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true

[[bin]]
name = "loader2"
test = false
bench = false
