[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[tasks.check]
command = "cargo"
args = ["check", "--target=x86_64-unknown-none"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--target=x86_64-unknown-none"]
