[package]
name = "arch"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true

[dependencies]
arbitrary-int = "2.2.0"
bitbybit = "2.0.1"
bitops = { path = "../bitops" }
primitives = { path = "../primitives" }

[lints]
workspace = true
