[tasks.build]
command = "cargo"
args = ["build", "--package=${LOADER_NAME}", "--target=${LOADER_TARGET}"]

[tasks.release]
command = "cargo"
args = ["build", "--release", "--package=${LOADER_NAME}", "--target=${LOADER_TARGET}"]
