[package]
name = "macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "*"
quote = "*"
rand = "*"
syn = { version = "*", features = ["full", "extra-traits"] }
